"""empty message

Revision ID: 765b3d5a1f62
Revises: 6976644f11e5
Create Date: 2026-07-08 19:42:19.863107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765b3d5a1f62'
down_revision = '6976644f11e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('follower', sa.Integer(), nullable=True),
    sa.Column('followed', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow')
    # ### end Alembic commands ###
